---
apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
    name: boo
    namespace: tbd
    labels:
        team: tbd
spec:
    pool: nav-prod
    config:
        cleanupPolicy: delete
        minimumInSyncReplicas: 1
        partitions: 6
        replication: 3
        retentionBytes: -1
        retentionHours: 47
    acl:
        - team: tbd
          application: helse-spokelse
          access: readwrite

